// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA2ioiE_exWDzlfi2T6tmUMGRBZGx5JhI',
    appId: '1:94213465783:web:eb5487f183e37696088f32',
    messagingSenderId: '94213465783',
    projectId: 'anon-c0a35',
    authDomain: 'anon-c0a35.firebaseapp.com',
    storageBucket: 'anon-c0a35.appspot.com',
    measurementId: 'G-9T63ZTCWD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhjFjUezdDNGuQHWOnjhFnroLrNBBtNHg',
    appId: '1:94213465783:android:434e2aa187a3f894088f32',
    messagingSenderId: '94213465783',
    projectId: 'anon-c0a35',
    storageBucket: 'anon-c0a35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv4fDtxI4-qVJ3UZNPMXLkeZaFZw0_Ru8',
    appId: '1:94213465783:ios:ac20c28390d531f0088f32',
    messagingSenderId: '94213465783',
    projectId: 'anon-c0a35',
    storageBucket: 'anon-c0a35.appspot.com',
    iosClientId:
        '94213465783-2om936a8rgv9ongkftqd31qavjgv5asa.apps.googleusercontent.com',
    iosBundleId: 'com.foumtech.wisper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv4fDtxI4-qVJ3UZNPMXLkeZaFZw0_Ru8',
    appId: '1:94213465783:ios:ac20c28390d531f0088f32',
    messagingSenderId: '94213465783',
    projectId: 'anon-c0a35',
    storageBucket: 'anon-c0a35.appspot.com',
    iosClientId:
        '94213465783-2om936a8rgv9ongkftqd31qavjgv5asa.apps.googleusercontent.com',
    iosBundleId: 'com.foumtech.wisper',
  );
}
